{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service-template.secretName" . }}
  labels:
    {{- include "service-template.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type }}
stringData:
  {{- toYaml (default (dict) .Values.secret.stringData) | nindent 2 }}
{{- end }}
