apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-environments
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/part-of: commerce-platform
spec:
  project: platform
  source:
    repoURL: https://github.com/vorobey5858/devops-project.git
    targetRevision: refs/heads/main
    path: platform-core/kubernetes/namespaces
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
