environment: stage
replicaCount: 3

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 768Mi

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack

podDisruptionBudget:
  enabled: true
  minAvailable: 1

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway

rollout:
  enabled: true
  analysis:
    enabled: true
