apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: demo-stage
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: commerce-platform
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
  namespace: demo-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: api-gateway-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SHARED_SECRET
      remoteRef:
        key: commerce-platform/demo-stage/api-gateway
        property: JWT_SHARED_SECRET
    - secretKey: UPSTREAM_API_TOKEN
      remoteRef:
        key: commerce-platform/demo-stage/api-gateway
        property: UPSTREAM_API_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-service-secrets
  namespace: demo-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: orders-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: commerce-platform/demo-stage/orders-service
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: commerce-platform/demo-stage/orders-service
        property: DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payments-service-secrets
  namespace: demo-stage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: payments-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: PROVIDER_API_KEY
      remoteRef:
        key: commerce-platform/demo-stage/payments-service
        property: PROVIDER_API_KEY
    - secretKey: PROVIDER_API_SECRET
      remoteRef:
        key: commerce-platform/demo-stage/payments-service
        property: PROVIDER_API_SECRET
